# Generated by Django 5.2 on 2025-08-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='face_image',
            field=models.ImageField(upload_to='face_images/'),
        ),
    ]
